module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: "USER_DETAIL",
    CUSTOMER_ADD_NEW: "CUSTOMER_ADD_NEW",
    DRIVER_ADD_NEW: "DRIVER_ADD_NEW",
    USER_ADD_NEW: "USER_ADD_NEW",
    EDIT_DRIVER: "EDIT_DRIVER",
    EDIT_CUSTOMER: "EDIT_CUSTOMER",
    EDIT_USER: "EDIT_USER",
    CONFIRMATION: "CONFIRMATION",
    DEFAULT: "",
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: "NOTIFICATION",
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    CUSTOMER_DELETE: "CUSTOMER_DELETE",
    DRIVER_DELETE: "DRIVER_DELETE",
    USER_DELETE: "USER_DELETE",
  },
});
