module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: "USER_DETAIL",
    CUSTOMER_ADD_NEW: "CUSTOMER_ADD_NEW",
    DRIVER_ADD_NEW: "DRIVER_ADD_NEW",
    CONFIRMATION: "CONFIRMATION",
    DEFAULT: "",
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: "NOTIFICATION",
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    CUSTOMER_DELETE: "CUSTOMER_DELETE",
    DRIVER_DELETE: "DRIVER_DELETE",
  },
});
